# Generated by Django 3.2.8 on 2021-10-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0002_auto_20200916_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazeteci',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
